config/routes.rb
PMAC::Application.routes.draw do

  get "address/new"
  get "address/create"
  get "address/destroy"
  match "address", to:'address#create', via: 'post'

  get "preorder/livraison"
  get "preorder/facturation"
  match "preorder/recapitulatif", to:'preorder#recapitulatif', via: 'post'
  match "preorder/payment", to:'preorder#payment', via: 'post'
  match "preorder/process-payment", to:'preorder#process_payment', via: 'post'
  get "preorder/confirmation"
  get "message/new"
  match "messages", to:'message#create', via: 'post'
  match "configurator/pvc" , to: "configurator#index", via: 'get'
  match "configurator/aluminium" , to: "configurator#indexAlu", via: 'get'
  match "configurator/store" , to: "configurator#indexStore", via: 'get'
  match "configurator/rideaux-metalique" , to: "configurator#indexRideaux", via: 'get'
  match "configurator/volet-roulant" , to: "configurator#indexVoletRoulant", via: 'get'
  match "configurator/accessoires" , to: "configurator#indexAccessoires", via: 'get'
  match "price", to:'configurator#price_data', via: 'post'

  resources :users

  resources :orders
  match "orders/next",to:'orders#next_step', via: 'post'
  match "orders/back",to:'orders#go_back', via: 'post'
  match "orders/cancel",to:'orders#cancel', via: 'post'
  match "orders/search",to:'orders#search', via: 'post'

  resources :line_items

  resources :carts

  match "show-cart", to: 'carts#show', via: "get"

  get "store/index"
  resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', as: 'root'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match "/users/search",to:'users#search', via: 'post'
  match '/forget-password', to: 'users#forget_pwd',     via: 'get'
  match "/process-forget-password",to:'users#process_forget_pwd', via: 'post'
  match '/reset-password/:token', to: 'users#reset_pwd',     via: 'get'
  match '/process-reset-password', to: 'users#process_reset_pwd',     via: 'post'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :addresses
  has_many :tokens
  has_one :person
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :login, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}

  before_save {self.login = self.login.downcase}

  scope :all_info, ->(id){includes([:addresses, :person]).find(id)}

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:index, :edit, :delete, :update]
  before_action :require_login, only: [:show, :user_edit]
  # GET /users
  # GET /users.json
  def index
    @users = User.all.order(:login)
    @criteria = UserCriteria.new
  end


  def forget_pwd

  end


  def process_forget_pwd
    hostname = request.host || "www.pmac-group.com"
    @email = params[:email]
    unless @email.blank?
      @user = User.where("login = ?", @email).first
      unless @user.nil?
        token = Token.create(:user_id => @user.id, :date_expiration => 1.days.from_now, :code => SecureRandom.uuid)

        OrderNotifier.send_token(token.code, @user, hostname).deliver
      end
    end

    render "forget_pwd_result"
  end

  def reset_pwd
    @valid_token = false;
    @token = Token.where("code = ?", params[:token]).first
    unless @token.nil?
      if @token.date_expiration !=nil && @token.date_expiration >= Time.now
        @user = User.find(@token.user_id)
        @valid_token = true if !@user.nil? && @user.state > 0
      end
    end
  end

  def process_reset_pwd
    if params[:password] == params[:confirm_password]
      user = User.find(params[:user_id])
      user.password_digest = BCrypt::Password.create(params[:password]).to_s

      if user.save
        token = Token.where("code = ? ", params[:token]).first
        token.date_expiration = nil #-10.days.from_now
        token.save
        redirect_to root_path
      else
        render "error/500"
      end
    end
  end

  def search
    email = criteria_params[:email]

    sql = []
    unless email.blank?
      sql << "login like '%"+email + "%'"
    end

    @users = User.where(sql.join(' and ')).order(:login)
    @criteria = UserCriteria.new(criteria_params)
    render "index"
  end



  # GET /users/1
  # GET /users/1.json
  def show
  end


  # GET /users/edit
  def user_edit
    id = session[:user_id]
    @user = User.find(id)
    if @user.nil?
      flash[:error] = "You must be amin to access this section"
      redirect_to new_user_path
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if user_params[:user_type].nil?
      @user.user_type= :normal
    end

    if user_params[:state] > 0
      @user.state = 1
    else
      @user.state = 0
    end

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|


      if @user.update(user_params)
        format.html { redirect_to users_path }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

  def criteria_params
    params.require(:user_criteria)
  end
    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :password, :password_confirmation, :user_type, :state)
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def setup_address(user)
    user.addresses.build if user.addresses.empty?
  end

end

app/views/users/_form.html.erb
  <%= form_for(@user) do |f| %>
      <%= f.hidden_field :id %>
      <table class="col-xs-8 table-striped">
        <thead>
        <tr>
          <th class="text-left">Emall</th>
          <th class="text-left">Type</th>
          <th class="text-left">Active</th>
          <th class="text-left"></th>
        </tr>
        </thead>
        <tbody>
            <tr>
              <td class="text-left"><%= @user.login %></td>
              <td class="text-left">
                <%=  f.select :user_type, options_for_select([['Admin', 'admin'],['Normal', 'normal']], @user.user_type) %>
              </td>
              <td class="text-left"><%= f.check_box :state%></td>
              <td class="text-left"><input type="submit" class = "btn btn-default" value="Enregistrer"/></td>
            </tr>
        </tbody>
    </table>
    <div class="clearfix"></div>
    <br>
  <% end %>

app/views/users/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><strong>Détail utilisateur</strong></h3>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<%= link_to 'Retour', users_path, class: :"btn btn-default" %>

app/views/users/forget_pwd.erb
<h4>Indiquez-nous votre email (qui correspond à votre nom d'utilisateur) pour générer un nouveau mot de passe.</h4>

<%= form_tag '/process-forget-password' do %>
    <fieldset class="col-sm-6" style="margin: auto">
      <div class="form-group col-sm-12">
        Entrez l'adresse email
        <div class="input-group col-sm-12">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
          <input class="form-control" type="email" placeholder="Email" value="" name="email"/>
        </div>
      </div>

      <div class="form-group col-sm-12">
          <input type="submit" value ='Envoyer', class="btn btn-primary pull-right">
      </div>
    </fieldset>
<% end %>

app/views/users/forget_pwd_result.erb
<div>
  Vous recevrez sous peu un email à votre adresse <%= @email%> pour composer un nouveau mot de passe.
<br/>
  <br/>
  <%= link_to "Retour à l’identification", sessions_path, class:'original' %>
</div>

app/views/users/index.html.erb
<h4>Liste des utilisateurs</h4>

<% if admin? %>
    <div class="form-horizontal">
      <%= form_for @criteria, method: :post, url: '/users/search', html: {class: 'col-xs-10'} do |f| %>

          <div class="form-group" style="margin-bottom: 5px">
            <%= f.label "Email", class:"col-xs-3 control-label" %>
            <div class="col-xs-9">
              <%= f.text_field :email, class:"form-control input-sm" %>
            </div>
          </div>

          <div style="float:right">
            <input type="submit" class="btn btn-primary" value="Rechercher"/>
          </div>
      <% end %>
    </div>
    <div class="clearfix"></div>
<% end %>
<br/>

<table class="col-xs-8 responstable">
  <thead>
    <tr style="background-color: whitesmoke;">
      <th class="text-left">Email</th>
      <th class="text-left">Type</th>
      <th class="text-center"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="text-left"><%= user.login %></td>
        <td class="text-left"><%= user.user_type%></td>
        <td class="text-center"><%= link_to 'Edit', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<% provide(:title, 'S’inscrire') %>
<div class="panel panel-default login" style="width:350px;margin: auto">
  <div class="panel-heading">
    S’inscrire
  </div>
  <div class="panel-body">
    <%= form_for(@user) do |f| %>
        <fieldset>
          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
              <%= f.text_field :login, class:"form-control", placeholder:'Identifiant' %>
            </div>
          </div>
          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon"><i class="glyphicon glyphicon-eye-open"></i></span>
              <%= f.password_field :password, class:'form-control', placeholder:'Mot de passe' %>
            </div>
          </div>
          <div class="form-group">
            <div class="input-group">
              <span class="input-group-addon"><i class="glyphicon glyphicon-eye-open"></i></span>
              <%= f.password_field :password_confirmation, class:'form-control', placeholder:'Mot de passe' %>
            </div>
          </div>
          <div class="form form-inline">
            <div class="pull-right">
              <%= f.submit 'Créer un compte', class: "btn btn-primary" %>
            </div>
          </div>
        </fieldset>
    <% end %>
  </div>
</div>

app/views/users/reset_pwd.erb
<%if @valid_token%>
    <%= form_tag "/process-reset-password", :id => 'reset-pwd-form', :class => "col-sm-8 form-horizontal", :style => 'margin:auto' do%>
        <div class="alert-danger error hidden">Les deux mot de passe ne sont pas pareils.</div>
        <input type="hidden" value="<%= @user.id %>" name="user_id">
        <input type="hidden" value="<%= @token.code %>" name="token">
        <fieldset>
          <div class="form-group">
            <label class="col-xs-6 control-label">Mot de passe</label>
            <div class="col-xs-6">
              <input type="password" class="form-control input-sm password" value="" name="password">
            </div>
          </div>
          <div class="form-group">
            <label class="col-xs-6 control-label">Comfirmer mot de passe</label>
            <div class="col-xs-6">
              <input type="password" class="form-control input-sm confirm-password" value="" name="confirm_password">
            </div>
          </div>

          <div class="form-group">
            <label class="col-xs-6 control-label"></label>
            <div class="col-xs-6">
            <input type="submit" value="Valider" class="btn btn-primary pull-right">
            </div>
          </div>
        </fieldset>
    <% end %>

    <% content_for :js do %>
        <script>
            $(function(){
                $('#reset-pwd-form').submit(function(e){
                    var password = $(this).find('input.password').val();
                    var confirmPassword = $(this).find('input.confirm-password').val();

                    if(password && confirmPassword && password === confirmPassword){
                        $(this).find('.error').addClass('hidden');
                        return true;
                    }
                    $(this).find('.error').removeClass('hidden');
                    return false;
                });
            })
        </script>
    <%end%>
<%else%>
    Le token n'est pas valide
    <br/>
    <br/>

    <%= link_to "Retour sur la page d'acceuil", root_path, class:"original"%>
<%end%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>