config/routes.rb
PMAC::Application.routes.draw do

  get "address/new"
  get "address/create"
  get "address/destroy"
  match "address", to:'address#create', via: 'post'

  get "preorder/livraison"
  get "preorder/facturation"
  match "preorder/recapitulatif", to:'preorder#recapitulatif', via: 'post'
  match "preorder/payment", to:'preorder#payment', via: 'post'
  match "preorder/process-payment", to:'preorder#process_payment', via: 'post'
  get "preorder/confirmation"
  get "message/new"
  match "messages", to:'message#create', via: 'post'
  match "configurator/pvc" , to: "configurator#index", via: 'get'
  match "configurator/aluminium" , to: "configurator#indexAlu", via: 'get'
  match "configurator/store" , to: "configurator#indexStore", via: 'get'
  match "configurator/rideaux-metalique" , to: "configurator#indexRideaux", via: 'get'
  match "configurator/volet-roulant" , to: "configurator#indexVoletRoulant", via: 'get'
  match "configurator/accessoires" , to: "configurator#indexAccessoires", via: 'get'
  match "price", to:'configurator#price_data', via: 'post'

  resources :users

  resources :orders
  match "orders/next",to:'orders#next_step', via: 'post'
  match "orders/back",to:'orders#go_back', via: 'post'
  match "orders/cancel",to:'orders#cancel', via: 'post'
  match "orders/search",to:'orders#search', via: 'post'

  resources :line_items

  resources :carts

  match "show-cart", to: 'carts#show', via: "get"

  get "store/index"
  resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', as: 'root'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match "/users/search",to:'users#search', via: 'post'
  match '/forget-password', to: 'users#forget_pwd',     via: 'get'
  match "/process-forget-password",to:'users#process_forget_pwd', via: 'post'
  match '/reset-password/:token', to: 'users#reset_pwd',     via: 'get'
  match '/process-reset-password', to: 'users#process_reset_pwd',     via: 'post'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def total_quantity
    sum = 0
    line_items.each { | item|  sum += item.quantity }
    sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart,only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart


  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(Cart.find(session[:cart_id]))
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to root_url, notice: 'Panier invalide'
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="recapitulatif" class="col-xs-12 clearfix">
<% if cart.line_items.empty? %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">PANIER VIDE</h3>
        </div>
        <div class="panel-body">
          Votre panier est actuellement vide. Vous n'avez aucune commande en cours.
        </div>
      </div>
    <a href="/">Retour à l'accueil</a>
    <div style="margin-bottom: 200px"></div>
<% else %>
      <div class="friezeBloc col-xs-12">
        <ul style="float:left" class="col-xs-10">
          <li class="first progres">
            Panier            </li>
          <li class="">
            Livraison            </li>
          <li class="">
            Récapitulatif            </li>
          <li class="">
            Paiement            </li>
          <li class="last">
            Confirmation            </li>
        </ul>
        <div style="float:right;margin-top:10px">
          <%= button_to 'Vider panier', cart, method: :delete, class: :"btn btn-default",
                        data: { confirm: 'Vous etes sur ?' } %>
        </div>

      </div>

    <div class="panel panel-default"  style="margin-top:100px">
      <div class="panel-heading">
        <h3 class="panel-title">Votre panier</h3>
      </div>
      <div class="panel-body">
        <div class="obj_table commandRecapTable">
        <table class="col-xs-12">
          <thead>
          <tr class="tableLine1">
            <th class="text-center th1">Article(s)</th>
            <th class="text-center th2">Prix unitaire</th>
            <th class="text-center th2">Quantité</th>
            <th class="text-center th2">Prix total</th>
            <th class="text-center th3"></th>
          </tr>
          </thead>
          <tbody>
           <%= render(cart.line_items) %>
          </tbody>
        </table>
        <div class="clearfix"></div>
          </div>
      </div>
      <div class="panel-footer">
        <div>
          <span style="display: inline-block;margin-right:50px"><strong>Total</strong></span><%= number_to_currency(cart.total_price, unit: "", separator: ",", delimiter: " ") %>€
        </div>
      </div>
    </div>
    <div style="float:right">
      <%= button_to "Continuer", preorder_livraison_path, class: :"btn btn-primary", method: :get %>
    </div>
<% end %>
</div>

<% content_for :js do %>
    <script type="text/javascript">
        $(function(){
            $('#recapitulatif tr.line-item').click(function(){
                $detailLine = $(this).next().toggleClass('hidden');
            });

            $('#recapitulatif button.delete').on('click', function(){
                var $this = $(this);
                var id = $(this).data('id');
                $.ajax({
                    method:"delete",
                    url:"/line_items/" + id + '.json'
                }).done(function(data){
                    $this.closest('tr.line').remove();
                    $this.closest('tr.line').next().remove();
                }).fail(function(){
                    console.log('echec');
                }).always(function(){
                    if($('#recapitulatif tr.line-item').length <= 0){
                        window.location.reload();
                    }
                });
            });
        })
    </script>
<% end %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% provide(:title,'Panier') %>
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<!-- START_HIGHLIGHT -->
<% unless @cart.nil? %>
    <%= render @cart %>
<%end%>

<!-- END_HIGHLIGHT -->