config/routes.rb
PMAC::Application.routes.draw do

  get "address/new"
  get "address/create"
  get "address/destroy"
  match "address", to:'address#create', via: 'post'

  get "preorder/livraison"
  get "preorder/facturation"
  match "preorder/recapitulatif", to:'preorder#recapitulatif', via: 'post'
  match "preorder/payment", to:'preorder#payment', via: 'post'
  match "preorder/process-payment", to:'preorder#process_payment', via: 'post'
  get "preorder/confirmation"
  get "message/new"
  match "messages", to:'message#create', via: 'post'
  match "configurator/pvc" , to: "configurator#index", via: 'get'
  match "configurator/aluminium" , to: "configurator#indexAlu", via: 'get'
  match "configurator/store" , to: "configurator#indexStore", via: 'get'
  match "configurator/rideaux-metalique" , to: "configurator#indexRideaux", via: 'get'
  match "configurator/volet-roulant" , to: "configurator#indexVoletRoulant", via: 'get'
  match "configurator/accessoires" , to: "configurator#indexAccessoires", via: 'get'
  match "price", to:'configurator#price_data', via: 'post'

  resources :users

  resources :orders
  match "orders/next",to:'orders#next_step', via: 'post'
  match "orders/back",to:'orders#go_back', via: 'post'
  match "orders/cancel",to:'orders#cancel', via: 'post'
  match "orders/search",to:'orders#search', via: 'post'

  resources :line_items

  resources :carts

  match "show-cart", to: 'carts#show', via: "get"

  get "store/index"
  resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', as: 'root'

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match "/users/search",to:'users#search', via: 'post'
  match '/forget-password', to: 'users#forget_pwd',     via: 'get'
  match "/process-forget-password",to:'users#process_forget_pwd', via: 'post'
  match '/reset-password/:token', to: 'users#reset_pwd',     via: 'get'
  match '/process-reset-password', to: 'users#process_reset_pwd',     via: 'post'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'

  

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :line_items
  has_many :orders, through: :line_items
  belongs_to :detail, polymorphic: true

  before_destroy :ensure_not_referenced_by_any_line_item

  def self.latest
    Product.order(:updated_at).last
  end

  private

    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    @latest_order = @product.orders.order(:updated_at).last
    if stale?(@latest_order)
      respond_to do |format|
        format.atom
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params[:product]
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <% @products.each do |product| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td class="list_description">
          <dl>
            <dt><%= product.title %></dt>
          </dl>
        </td>
        <td class="list_actions">
          <%= link_to 'Show', product %><br/>
          <%= link_to 'Edit', edit_product_path(product) %><br/>
          <%= link_to 'Destroy', product, method: :delete,
                      data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
  <% end %>
</table>
<br />
<%= link_to 'New product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>